// next imports
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

// react imports
// image imports
// component imports
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href={"/about"}>
          <p>Click me!</p>
        </Link>
      </main>

      <Footer />
    </div>
  )
}
